[project]
name = "dave3625-host-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scipy>=1.16.1",
    "seaborn>=0.13.2",
]
